url: "https://rede-dsbr.github.io"
baseurl: "/documentacao-desenvolvimento-pnp"

title: "Documentação de Desenvolvimento PNP"
subtitle: "Plataforma Nilo Peçanha"
footer: "Documentação elaborada pela Rede DSBR."
search_engine: "lunrjs"

plugins: []
